---
title: TERMをtmux-256colorにする
tags:
  - tmux
  - terminal
  - vim
kind: note
date: February 15, 2021
---

* なぜやるのか

かねてよりmacOSが重くなることに困っていて、 [[https://github.com/tmux/tmux/issues/353#issuecomment-202726966][macでtmuxとvimを使うとvimがすごく重くなる]]
を見つけました。

結果論としては「これがパフォーマンスをよくする」というわけではなさそうでしたが、
とりあえずtmuxを使っているので、揃えることにしました。

* 前提知識

** そもそもTERM環境変数とは何か

=$TERM= は、ncursesなどが使っている *terminfoライブラリ* の動作に影響する環境変数です。
この変数で「なんの端末を使っているか」を設定し、terminfoライブラリがそれに応じて出力を変えているため、
cursesを使用する開発者は端末の差をあまり考えずに様々な端末に対応したソフトウェアを書くことができるのです。
(エスケープシーケンスとか決めている)

実は端末エミュレーター(とそもそもの端末)には色々な種類があります。有名どころだと
=xterm=, =cygwin=, =guru=, =vtシリーズ= などでしょうか

筆者もそこまで詳しくないですが、途方もない数の仕様の端末が存在しています。
それらを共通のインターフェースで扱えるようにするのが =terminfo=,
そして「今使っている端末」を設定するのが =TERM= 環境変数、ということです。


ちなみに余談ですが、=terminfo= で使用されるデータはmacの場合、
=/usr/share/terminfo= に格納されています。

** terminfoエントリ

terminfoエントリは、

info:terminfo


* 手順

+ [[#tmux.confで、tmux内でのTERMを設定する][tmux.confで、tmux内でのTERMを設定する]]
+ [[#terminfoエントリーを追加する][(terminfoのエラーが出る場合) terminfoエントリーを追加する]]

** tmux.confで、tmux内でのTERMを設定する

[[https://github.com/tmux/tmux/issues/353#issuecomment-202726966][前出のリンク]]で説明されているように、
以下を =~/. tmux.conf= (または使っているtmux.confファイル)に追加します

#+begin_src tmux
set -g default-terminal "xterm-256color"
#+end_src

** terminfoエントリーを追加する

筆者の環境(macOS+homebrew)では、terminfoエントリーがないと怒られてしまいエスケープシーケンスが全く使えなくなりました。

しかし、実はhomebrewもきちんとterminfoエントリーを作成してくれています。
=/usr/local/opt/ncurses/bin/infocmp=
には作成されたエントリーが保存されているのですが、ここは残念ながら参照されません。

そこで、[[https://github.com/tmux/tmux/issues/1257#issuecomment-581378716][tmuxのissueにあった方法]]
で =/usr/bin/infocmp= に追加します

#+begin_src sh
$ brew install ncurses
$ /usr/local/opt/ncurses/bin/infocmp tmux-256color > ~/tmux-256color.info
$ tic -xe tmux-256color tmux-256color.info
# This creates a complied entry in ~/.terminfo
$ infocmp tmux-256color | head
#       Reconstructed via infocmp from file:
#       /Users/libin/.terminfo/74/tmux-256color
tmux-256color|tmux with 256 colors,
#+end_src

* 参考リンク

+ https://github.com/tmux/tmux/issues/353#issuecomment-202726966
+ [[https://chakku.hatenablog.com/entry/2018/07/22/040129][tmux上でtmux-256colorを使用する(mac) -- ちゃっくのメモ帳]]
+ https://github.com/tmux/tmux/issues/1257#issuecomment-581378716
