* 秋葉原和堂に行ってきた
  :PROPERTIES:
  :DATE: [2021-09-12 Sun 23:47]
  :TAGS: :Akihabara_Wado:
  :BLOG_POST_KIND: Diary
  :BLOG_POST_PROGRESS: Published
  :BLOG_POST_STATUS: Normal
  :END:
  :LOGBOOK:
  CLOCK: [2021-09-12 Sun 22:59]--[2021-09-12 Sun 23:48] =>  0:49
  :END:
  
  今日は仕事が早めに終わったので、折角だからどこかで御飯食べて帰ろ~と
  思った矢先に思い出したのが秋葉原和堂だった。
  秋葉原和堂は存在こそ知っていたものの、その雰囲気と

  ---

  意を決して階段を降りる。
  そもそも地下なことも把握していなかった。
  階段を降りつつ、最初で最後の踊り場で下を見てみると、そこには重い両開きの
  扉が一つ。
  
  「ドア」ではなく「扉」がもっともふさわしいと思うような、
  「この世俗と奥の空間を区切る」ような雰囲気のある扉だった。

  
  この扉の前で、既に少し雰囲気に圧倒されている。
  扉の装飾も綺麗で、この身で触れることも躊躇うような美しさと重さのある
  雰囲気を漂わせていた。

  
  まだ引き返すこともできる。
  まだ、ここなら取り止めることもできる。
  

  そんな感情すらよぎる程に雰囲気に圧倒されていた。


  先程もした気がするのだが、ここでもまた意を決して右側の扉に手をあてて、
  力を入れ、ついにこの秋葉原和堂に踏み入れた。

  扉を開けた先、すぐに目に飛び込んできたのは豪華な、それでいてもうるさくなくもの静かな
  威厳のあるソファと絨毯だった。
  
  誰が座るわけでもなくそこに置いてあったそれらは、恐らく装飾の一つにすぎないのだろうなと思うが
  ここの世界観・雰囲気を物語るには十分だった。
  

  そこに目を引かれるのもつかの間、左手側に受付が見える。
  店員さんが二名。
  
  受付にはAirPayだとか様々なお土産・コラボグッズだとか近代的なものが置いてあるにも
  かかわらず「大正」の雰囲気に上手いこと溶け込んでいた。
  
  店員さん方の服装も、大正時代にあったものと近しいのかは分からないけれどとても
  綺麗で、溶け込んでいた。

  
  ~~
  
  店員さんに関して一つ言えば、髪色を染めている方が何人もいらっしゃったにも係らず
  服装やお店の雰囲気から少しも逸脱せずに溶け込んでいたのが本当に驚いた。
  
  秋葉原和堂のツイッターに掲げられている「『大正浪漫』と『調合』がコンセプト」、
  まさにこれを体現しているなと今特に思う。
  
  ~~
  

  事前にTwitterやサイト等で色々と見ているものの「ご利用は始めて」なので
  受付の店員さんに頼み方等を教わる。

  ベル若しくは備え付けのQRコードから注文が可能らしい。
  「大正」と「令和」のコンビネーション...調合...調合ってそういう意味なのか
  分からないけど。

  
  受付でカフェを選択し、メニューを受け取ってフロアへ進む。
  進むといっても横を向いたらもうその場所なのである。
  そちらを向いた瞬間に、一瞬固まってしまった。
  
  今迄散々TwitterやInstagramで拝見させて頂いていた景色とはいえ、
  実際に目の当たりにすると何だろうな、雰囲気が凄い違う。
  本当に異世界に来たような、ここだけ時の流れが違うような、
  非日常感がとても強い光景だった。
  タイムトリップしたような気分になった。

  なんとこの時はたまたまカフェ側には他のお客様がいらっしゃらなかったので、
  自由に席は選び放題だった。とりあえず、壁を背にできるソファに座る。

  とても、良い...

  座って一息付き、テーブルの上を見渡してみると見付かるのが先程話にあったベルとQRコード。
  QRコードは紙に印刷されていたが、ベルは本格的に「ベル」だった。
  「ベルの音がなる機械」ではなく「ベル」だった。
  
  そのベルは、正直初めて見たかもしれない...というくらいに想像通りの「ベル」で、中にある長い
  部分が結構長かった。そしてここにも素敵な装飾...
  
  
  メニューを開こうとして、メニューの表面の文様が見えたがこれもとても綺麗に出来ている。
  なんだろう、実際には見たことがないが昔の本にありそうな装飾。
  金色で縁取られ、花のような蔦のような模様が並んでいる。
  綺麗...
  
  綺麗なのはいいんだが、私は頼むものを決める必要がある。ずいぶんと(特に紅茶の種類で)悩んだ末、
  料理はナポリタンで紅茶は「この料理にあう紅茶お勧めありますか？」にすることにした。
  

  ---
  眠い。ので書きたい所先に書く
  ---

  清算を終え、和堂の扉に手をかける。
  ...ここから外の世界へ戻るのには少し時間が必要だった。
  でも出なければならない。なぜならここはお店の入口なので...

  少し躊躇ってから、覚悟をつけてえいっと開けて外に出た。
  そして外に出たのと同時に「令和現代日本」に帰ってきたのを感じた。
  よくも悪くも私の本来生きている世界線。
  
  最初はここから「秋葉原和堂」の世界へ入るのに躊躇していたけれど、
  最後にはこちらに戻ってくるのを躊躇するようになってしまっていた。
  かかっていた曲といい、内装といい、メニューといい、店員さんといい、
  普段とはとても異なった世界だったけれど謎に安心感と落ち着きを感じていた。

  
  普段大体この仕事終わりは精神的に相当疲れていて、家に帰ってからもすぐ疲れて寝て
  しまうことが多かった。
  が、今日は秋葉原和堂のおかげで大分精神が楽。居心地の良さ、緊張の解れよう、リラックスさが
  半端じゃない。
  「また一週間頑張るか~~!!」という気力すら湧いてきた。


  普段から通うには少し御高いけれども、一ヶ月に1回とか自分のご褒美として秋葉原和堂に来るのが良いのかも
  しれない、と感じた。


  あとがき
  
  あと眠いながら書いてるので誤字脱字諸々すまん頭がまわらない。
  でも当日中にどうしても記録しておきたかった...
  
  
  
  
