* ALLELOSPHERE Reverse Real v1
  や~~~最初はみあちゃんのあちゃんだけ見て流し見しようかと思ってたけど
  みんな良だったので通しで見てしまった。

  今見返してて気が付いたけど、ライブ中殆どはライブ側にコメしてるのでTwitterに
  記録があまりない...

** 各回の感想
*** [[twitter:Raiaxxxia][来栖らいあ]]
    2曲、ファンの方と作ったオリ曲？とその次にリバリアで作った曲のお披露目!

    一曲目は電車の中で聞いていたので実はあまり聞けてない...かわいかったのだけ
    覚えている。
    
    二曲目、 Dear Darlin(?) はASMRが入ってたりして結構ぞくっとした...
    車内で聞いてたんですがこう...非日常感やば...
    曲としてここまでASMR入れ込んでたの聞いたことなかったのでそれだけですごく良でした。
*** [[twitter:reco_v][織田りこる]]
    Live2Dでの参加!
    大体が3Dになってると思ってたのでびっくりした。
    でも、中々3Dだと(今回は)実現しにくい演出だとかが沢山で良きでした。
    
    かわいい+ウサギさん+桜吹雪っていうのが
    みあのあ(特にのあ)に似たものを感じてちょっと嬉しみがあった。
    
*** [[twitter:asuka_shovel][火渡飛鳥]]
    声優の卵とのこと。
    今迄の二人と打ってかわって渋い、力強い声での歌唱でした。
    かっこよい。
    盛り上ってるなぁぁぁ!!!
*** [[twitter:honey_kotoko][琴子]]
    大分の御当地VTuber。
    MVとして作り上げられており、映像として凄い。
    大分の有名なものとかが沢山入ってたらしいけど私大分分からん+移動中で
    画面があまり見れなかったのが残念orz

    とても綺麗で「大和撫子」という雰囲気の映像でした。
*** [[twitter:yozakura_mia][夜桜みあ]]
    我らが!!!!!!みあちゃん!!!!!!!!!!!

    フルトラでは動けず(多分)facerigとかを使ってたと思うけど、
    動いているみあちゃんが見られただけでも嬉しかったです。
    「アリ~~ナ~~!!」ってやりたがってるのがかわいい。
    「技術ってしゅげ~~~」じゃないんだよ貴女のかわいさもしゅげ~~~だよ。
    技術ってほんとしゅげぇ...

    blooming magicはコール&レスポンスもある曲で、みあちゃんが
    コール&レスポンス講座してくれた。そのお陰でみんなやってくれてありがてぇ...
    黒猫さん以外の方もみんなコール&レスポンスしてくれていて、めっちゃ
    会場全体で盛り上りました。とても良い。
    
    ただね!!!キーボードで打つには間隔が短いのよねあのコール!!!!!!
    全然追いつきませんでした。
    追いつかなかったけど楽しかった。
    声でコールしたらそのまま届いてくれませんかね？？ダメ？？？はい...

    夜桜みあのかわいさが世に知れちまったな~~~これはみんな
    見るしかないな~~ほんと。

    ...最近の切り抜き作っておけばよかったなって思ってます!!うん!!!!
    絶対そうするべきだったねぇぇぇぇ!!!!!
    

    ちなみにさらっと「ありがと~!」とか言ってた気がしますが
    ありがとうはこっちなんだよなありがとぉぉぉぉぉぉあのさぁぁぁあぁぁ
    存在してくれててありがとうなぁぁぁぁぁぁ


    すき
*** [[twitter:ringo_0_0_5][九条林檎]]
    林檎さまだねぇ。うん。
    流石の林檎様、というステージでした。

    衣装も麗しくかつかっこ良い。
    セルフカメラらしいし、それでいて歌も踊りもしっかりとこなす。
    流石なんだよな...
    
    ステージで林檎様が出る度にコメ欄が「麗しい...」「征服して!」になるのが
    とても好きです。こんなに本人の雰囲気がにじみ出るコメ欄他にあるだろうか。
    +あ、名取のとことかはある意味滲み出ていますg+

    かっこよい+麗しいが本当に素敵でした。
*** [[twitter:misyasamadayo][魅紗]]
    一目見てわかるこのたたずまい。
    実は前回のオリ曲コンピの時に知ってそこからフォローしておりましたが、
    相変わらず歌が綺麗。声の出し方とか関係なしに凄く綺麗。

    曲も御姿も美しくて最高でした。
*** [[twitter:yozakura_noa][夜桜のあ]]
    ア゛イ゛ド゛ル゛!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

    今日ののあちゃんはガチでアイドルでした。
    導入のカメラワーク・歓声からのパーティクルの演出とても綺麗でした。

    サビ以外の振り付けは自分で考えたって言ってたけどかわいかったでし...
    りんりんちゃん作の衣装も素敵でした。
*** [[twitter:0w0_YUZU][柚月ゆず]]
    Live2Dでの参戦...と思いきや超綺麗な3D!!
    多分MMD...?
    沢山動いていてとても楽しい!

    衣装も、姿もステージも演出も綺麗でした。

    海の上のステージ、というのがアイマリンプロジェクトのMarine Dreamin'と
    重なって懐しい気持ちになりました。
    私の3DCGとの馴初めがMarine Dreamin'なので...

    綺麗なステージを見て、「あぁ我もCGやりたいな...」となりました。
    声も素敵でした。
    
---------
 あの、ここらへんからライブ視聴後数時間経って書いているので段々と内容を忘れています
---------

*** [[twitter:V01Yume][V01 YUME]]
    声が綺麗...
    お目目も綺麗...YU"ME"だけに...

    はい。

    くっ...?って体かしげてるのがとてもかわいかった。
*** [[twitter:mewmewsugar][幸糖ミュウミュウ]]
    我らがA2Pのミュウミュウちゃん!!
    休止中だったのを途中で思い出しましたが、そんな中の出演って中々エモでは...
    
    私はそこまでガッツリ追ってなかったけれど、待ち侘びてたファンも
    多かったろうなぁという気持ちで見ていました。

    振り付けがかわいい!!とてもかわいい!!
*** [[twitter:Noakun_RET][御兎木乃天]]
    動画での参戦。
    MV調に仕上がっていて、童謡？民謡？的な曲と合う世界観で引き込まれました。
    すっ...と聞き入っておったよ...
    
*** [[twitter:Sakura_Maychan][サクラメイ]]
    大トリ!
    最初っからめちゃくちゃ元気な声・元気な動きをしていて、
    一気にテンションが上がりました。
    先程のしんみりさは何処へ...
    
    歌っている間もずっと元気で見ていて元気が貰えるタイプの子でした。ありがたぅ
