* 最近話題のゆっくりに関連した商標に関しての考え
  :PROPERTIES:
  :DATE: [2022-05-16 Mon 11:45]
  :TAGS: :商標法:
  :BLOG_POST_KIND: Memo
  :BLOG_POST_PROGRESS: Empty
  :BLOG_POST_STATUS: Normal
  :END:
:LOGBOOK:
CLOCK: [2022-05-16 Mon 11:45]--[2022-05-16 Mon 12:16] =>  0:31
:END:
  
** 始めに
私は法律の専門家ではありません。知財法に関してちょこっとだけ齧りましたが、
ほんとにちょこっとだけです。

ここで書かれていることは個人的な考えであり、
一応対応する法律等は明記するものの間違っている可能性があります。

又、ここでの知識は知的財産管理技能検定3級公式テキスト改訂11版を
主に元としています。

** 例の問題
5/15、YouTubeチャンネル「柚葉 / Yuzuha」さんが、
「 ゆっくり茶番劇」という文字商標を取得したことを[[https://twitter.com/Yuzuha_YouTube/status/1525607600250712064?s=20&t=JDWJ3zpE2P4Biw8Kkd_SwQ][twitterで公開]]しました。

そしてそれに伴い、使用料10万円を請求するとのことで話題になりました。

詳しくは[[https://nlab.itmedia.co.jp/nl/articles/2205/15/news045.html][ねとらぼさんの記事]]
等を確認してもらえると良いかと思います。

** 私の考え
*** Q. 第三者が勝手に商標を登録することは可能なのか？
可能だと思います。
商標は法人でも自然人でも登録可能であり、要件も満たしていれば問題がないです。
登録の要件は[[https://elaws.e-gov.go.jp/document?lawid=334AC0000000127][商標法]]3条で定義されており、知的財産管理技能検定3級公式テキスト改訂11版
を参考にして簡単に纏めると以下のようになります:


+ 自己の業務に係る商品等に使用すること 
+ 識別力を有すること
  

「自己の業務に係る」という点に於いて、柚葉さんのYouTubeを見てみると
(一応)「ゆっくり茶番劇」という名称を使っているので、
これは満たしていると判断されるかもしれません。


識別力については謎な所で、個人的には「識別力はない」のではないか？と考えています。

例えば、YouTubeで「視聴回数順」のソートで軽く検索かけてみた所16件あり、
恐らく文化圏的にニコニコの方にもっとあるであろうことを考えると
少なくともこの界隈内で識別するのは難しいと言わざるを得ません。

が、まぁ一部の界隈だけというのもまた事実ではありますね...そういう面
で実体調査をパスしたのかもしれません。
  
*** Q. ここから無効にする方法は？
利害関係者であれば「商標登録の無効の審判」を請求することができます。
([[https://elaws.e-gov.go.jp/document?lawid=334AC0000000127][商標法]]46条)

今回の場合、「ゆっくり茶番劇」はかなり昔から使われている名称であるため、
「普通名称」として無効を主張できないんかな？と思っています。


但し、その全てについて「自分が作ったものです」と言われると面倒な気はします...
証明できるもの出せないから出来ないか...?

*** Q. 我々がするべきではないことは？
*爆破予告・殺害予告・名誉毀損等の行為です*

そもそも、それらのものは許されるべきではない、という事は言わずとも同感していただけると
思います。
それでも、感情的になったあまりそういった手段に走ってしまう人がいるような情報が流れてきます。
これは、逆に訴えられてしまったり自分達にとって不利に働くだけなのでやめて
欲しいなぁと思いながら見ています。

法に則って行われた手続きには法に則って解決しようねぇ

