* 全部ホントで全部ウソ / ナナヲアカリ -- の感想文
:PROPERTIES:
:DATE: [2023-03-28 Tue 03:35]
:TAGS: :music:
:BLOG_POST_KIND: Memo
:BLOG_POST_PROGRESS: Published
:BLOG_POST_STATUS: Normal
:END:
:LOGBOOK:
CLOCK: [2023-03-28 Tue 03:39]--[2023-03-28 Tue 03:40] =>  0:01
:END:

中々ない、「感情がそのまま文字を書きたがった曲」だからメモを残しておく。尚今回はガチのメモなので、全
然整理はされていない。

曲: [[https://www.youtube.com/watch?v=SlBmv7w1VqY][全部ホントで全部ウソ / ナナヲアカリ - YouTube]]

歌詞的には自分とは真逆な人生を歩んでいる人達の曲だけど、だから自分とは相容れないけれど、何か心にひっ
かかるものがある曲だった。そういった生き方をしている人達にとっては素敵な曲だろうな、と思うような曲だった。


実際、人生日替わりコーデな生き方をしている人達の方が多いんだろうし、自分のとても仲の良い(と勝手に思っ
ている)人もそういう人だから全然その生き方に対して批判的であることはない。そういった生き方をしている
動機は勿論人にもよるんだろうけど、自分自身が傷付かないように、だったり他の人が傷付かないように、だっ
たり他の人にプラスなものを与えるように、だったりすると思うから、それが一概に悪いことだとは思っていな
い。(「一概に」と表記したのは、多分だけど悪用する人達も一定数はいるだろうから、そこを排除するため)


ただ、そういった生き方をしている事で悩んでいる事もあるみたいなのは観測した事があるから、それに対して
「このままでいいのだ」「ぶっちゃけ世の中大半は皆同士」っていってくれるのはきっと救われる人達多いだろ
うなぁ、などと。「どれが本当の自分か分からない」みたいなね。 


こういう、なんか明るそうに見える曲なのに「正直自分のこともよくわかんない」って言っているの、何も考え
ずに「このままでいいや!」って言っているわけじゃないってのが伝わってきて、色々悩んだ上でのってのが伝
わってきて、すきだよ。独自解釈だけど。


私は極端に「自分自身が嘘をつくこと」が嫌いで、嘘も方便という言葉を真と考えつつも自分には適用出来無い
タイプの人間。や、少なくとも自分はそう思っている。え、そんな嘘あんま付いてないと思っているけどついて
たらゴメン...(あでもネットリテラシー的に自分の個人情報はある程度カモフラージュはしているよ、そこは流
石に色々まずいので。嘘は書いていないが。)


外面コーデも壊滅的だが内面コーデは最早選択肢を持っていないというレベルでセットがない。なので一戸建て
にずっと住んでる安心感？はすごいあるが必要な環境変化への適応力はない。


なんかどーーでもいいことや嘘を付いた方が得かつ誰も損しない時でも嘘を付くのが気持ち悪く感じてしまう。
テストの採点が間違っていて点数が不正に高くなってしまった時にそれを言いにいかないと気がすまなかったり。
最近はあんまり嘘かなきゃいけないような場面に出会っていないのでそんなに事例が思い付かないな...
いうたらツイッターに全部書き込んでしまうのもそう。他の場所でツイートをすることを「嘘をついている」と
いう風に感じてしまう。自分自身がね。他の人がどこでツイートしようが別に嘘つきとは思わないし、なんなら
それが普通の使い方だと思っている。アカウント分けるのが普通だと。まぁなので気にしていない(気にはなる
かもしれんが)。私がちょっと頑固なだけ。


正直自分の方がかっこわるいし普通に不便だし他人への不快感は高い人生をしているだろうな。多分頭が堅いと
も言う。また違った生き辛さがある気はする。協調性のかけらもないとも言うので、真似はしない方が良い。


でも私は「かっこよくなること」とか「人に好かれること」を完全に放棄しているのであまり悩んでいないんだ
と思う。その割には寂しそうなことあるって？そりゃあるわ。でもある程度諦めと解決方法が他にあるってだけ。
あというたら偶に向こうから話し掛けてくれて話しをしてくれる人がいるのでそれで十分みたいな所ある。後は
推しの存在には大分助けられている...本当に...でも大分依存しすぎだから気をつけなきゃいけないけど。


まぁ細かに自分の事書くエントリでもないか。


ぶっちゃけいっつも"ぶってる"あんたたちの方がかっこいいな、と思うときも沢山あるよ。中々ストレスかかる
じゃん。どこでどういう顔をしていたかとか、どんな話し方してたとか、どんな性格してたとか覚えてないとい
けないし、毎回それで対応しないといけない。正味私はそれが出来る気はしないから、そうやって他の人のこと
考えたりすることから逃げてるとも言える。それに、いうなれば私の生き方は「周りを気にしない」みたいなも
ので正直一番良くない自覚があるよ。だから、だからこそ、そうやって悪い意味ではなく全部ホントで全部ウソ
な人生を生きている人達がこうやって「これで、このままでもいいのだ」って思えると良いなってとっても思っ
た。


私はこの曲を名取の2023年のお誕生日ライブから聞いて、かつ推しの夜桜みあの同時視聴枠で見たから余計に色々
考えてしまった。あんまりこの表現はすきではないからボカしてかくが、ようするに彼等彼女等は一種「全部ホ
ントで全部ウソ」なわけで。そんな存在でこれを歌うって色々と考えることがあると思うんだ。表現者として
「ステージ」を作っている名取自身は特にね。夜桜みあは(これは勝手に思っている事なので間違っている可能
性も大分ある)大分感性が強いし他の人のことも考える人なので、名取が色々考えているのを色々想像したりと
か、普段から活動していて色々と考える部分があるんじゃないかなぁと勝手に思っている。全く分からん妄想だ
けどさ。


あと名取に関して言えば、この若干「メタ」に触れるような意味にも取れる楽曲を選んだのってそれなりな覚悟
があったんやないかなぁって気持ちを抱いた。や、そもそも今回のライブのテーマ的にも凄くピッタリなんだけど
も、ダブルミーニング的になっていると思うんだよね。そもそもの一人の人間(バーチャルだとしても)としての
名取さな自身のこと(ライブテーマ)と、そして"Vとしての名取"と"サナトリウムにいる名取"という関係性のこ
とっていう双方に於いて、「全部ホントで全部ウソ」っていう。まぁある意味で「メタ要素」とも取れる患者姿
の事にライブの流れとして触れたので、それ自体ももうステージの一部に取り込まれているんだけど、大分覚悟
を決めての構成じゃないかなぁってにわかながらに思っていた。



と、いうことで、久々に色々文字が浮かんでくる楽曲に出会えたので名取に感謝、そしてそのキッカケをくれた
みあちゃんに感謝、といった所。しかも自分と正反対な存在に関しての歌でなるのは珍しい経験だった。
