* 夜桜みあのかわいさについて
  :PROPERTIES:
  :DATE: [2023-03-16 Thu 02:27]
  :TAGS: :夜桜みあ:
  :BLOG_POST_KIND: Memo
  :BLOG_POST_PROGRESS: Published
  :BLOG_POST_STATUS: Normal
  :END:
:LOGBOOK:
CLOCK: [2023-03-16 Thu 02:27]--[2023-03-16 Thu 02:33] =>  0:06
:END:

これ書きながら思ったんですけど、夜桜みあの魅力の中から「かわいさ」だけを抽出するのって難しいんですよね。なので一部
他の魅力について語るオタクが出てくると思うんですけど目を瞑ってもらえると嬉しいです。では。
  
** 経緯
今日のみあちゃんの配信にてかわいさに関してのレシート(長文マシュマロのこと、基本嫌われる)書くか~~？？みたいなノリになり、試しに
書き出してみた所全然文字数オーバーすることが分かったのでどうせならブログに残しておくことにしました。
  
** 夜桜みあちゃんのリンク系
+ [[https://twitter.com/yozakura_mia][Twitter]]
+ [[https://www.youtube.com/channel/UCH3tRsAvHSsTi1LDC7l_PDA][YouTube]]

** 注意事項
+ 一度も推敲していないです
+ ですます調の統一を今回は大分サボりました
+ ただのオタクの怪文書です
+ 今思いつく限りしか載っていないので抜けはあるかも

** 声
まずそもそも声がかわいいね。や、これは本当に沢山ある中での一要素でしかないんですけど、やっぱり夜桜みあに興味を持った
最初のキッカケも声だったし誰もが分かるかわいさっていう面でまず第一に持ってきたいところです。  
声はねぇ...ほんとうに...ほんっっとうにかわいいんですよ。夜桜みあの声は(両声類とか程ではなくとも)結構バリーエションが
あると思っていて、かわいさに分類されない「かっこよさ」みたいなのもありつつかわいさの魅力もガンガンあるんですよね。
あ、「かっこよさ」とかも正直めちゃくちゃすきなポイントなんですけど今回は「かわいい所」なので一旦パスで。


あとこれはある程度の時間推させて頂いているからこそ分かる所なんですけど、大分声がお姉さんへ成長しましたね。
正直に言うと昔の方がもっとロリっぽかったように思っていまして、昔でいうとロリ100%だった所をロリ70お姉さん30くらいに
なっているように思います。でもたまにロリ100%に戻ったりするんで、あなたもしかしてある程度コントロールできる...!?み
たいな気持ちでいます。まぁ出来るか。...あざとくない...??  
(ここに関して、ちょっと配信に慣れたりして声のトーンが下がったりもしたのかなぁ、と思ったりもしていますが、それはそ
れで嬉しくて良い。正味どんな声でもすき。かわいいジャンルとは違うけど、お友達の方々と喋ってたりゲームやって煽ってた
りする時のような通常時ぽい声もめちゃすきなんよね。頑張ったけど出なかった大蛇丸とかもね。喉潰さんようにね)

完全にロリ意識してるだろって時の声は本当にとにかく甘い。とにかく甘くてかわいい。は？？なんですか？？？かわいいんで
すけど...でも甘いのになんだろ、嫌な感じがないというか。ただただ甘いチョコレートだと沢山食べると「もう今はちょっと
いいかな...チョコだけに」ってなるんですが夜桜みあの場合はこう、いくらでも食べれる甘いチョコレートみたいな所があり
ます。これは個人の好み的なものもあるのかもしれないですが、私には丁度良い塩梅でした。
あと多分私がそれまで甘いかわいさみたいなの触れてこなかったのもあって、大分落とされましたね。

普通にしている時？でもスタンダードにかわいいですよね。何？？多分そこまでかわいさ意識して喋ってないと(勝手に)思って
いるんですけど、とてもかわいいんですよね。でもこれは甘さとはちょっと違うかもしれない。単純に私がすきな周波数帯とマッ
チしているだけ説はあります。

** 仕草
次!やっと次だよちなみにここまでで1000文字くらいあるぽいですね。え...?
次は仕草です。夜桜みあの仕草。これは例えばウインクであったり、歌いながらめちゃノリノリだったり、そういうところを指
しています。頑張ってウインクしてるのかわいくない？？配信の最後に毎回ウインクしてるの、かわいくてとても良いよね。
まぁ頑張ってって言ってもみあちゃんはウインク得意だから実際そんなに頑張っているわけじゃないんだろうけど、でもこう...ウ
インクした後ドヤッ...ってしてるの、毎回「頑張ったでしょ!」「上手く出来たでしょ!」って自慢されている気がしてとても
かわいいなぁと思っています。まぁこれはまた後ほど。

ノリノリなのかわいいのはそれはとてもそうじゃん。それももうそのままじゃん。だって...ねぇ？そこで夜桜みあがめちゃ動
いているんだよ？？もう動いているだけでかわいくない？？？それを言ったら存在自体のかわいさ的な話になるので一旦置いて
おくことにします。一旦置いておくことが出来る猫です。おあずけ。簡単に言うと「ノリノリで楽しそうな状態」っていうのが
かわいいよねっていう話です。

** 反応
何かしらのイベントが起こった時の反応の仕方がかわいいと私の中で話題に。何かへの反応として出る声だとか、驚き方とか、
そういった所です。実は結構細かい所で沢山あるんだけれど、逆にいうと細かい所すぎてあまりしっかりと覚えていないみたい
な所があります...オタクくんさぁ...??
何か考えている間に言葉に出ちゃったりするのもかわいいよね。コメントにしろ自身の行動の結果にしろゲームからのイベント
にしろ...喋りながらさらっと物真似になっていたり、さらっと歌い出していたり、さらっとだじゃれを言うてたりとか。例が
雑だって？そんなことないが...?そんなこと言うのは君か？

なんか知らんけどやたら楽観的な反応をしている所もかわいいな...って思ってたりはします。親不知の話の時に本人めちゃピ
ンピンしていた話とかね。

「歌詞歌詞歌詞歌詞歌詞...くしくし、僕ハム太郎なのだ!ヘケッ」とか。おうた中に歌詞が抜けた時、あわてつつもメロディラ
インには載せながら色々話しているのもすき。


でもここはあれかも、かわいいもそうなんだけど「反応の豊富さ・面白さ」みたいな独立した魅力でもあるから「かわいいも
の」って限定して考えるのはあまり向いていないかもしれない。

** 態度変化
す~~ぐイキる所とかね。それでいてまたすぐフラグ回収して泣きべそかいたり...んでまたす~~ぐイキったり。
なんか上手くいった時とかにめちゃめちゃドヤっているのもかわいいねぇ...って目を細めてしまいます。おじいちゃんなので。
自慢気になってるのもかわいいね...沢山褒めてあげようねぇ...ってなる。
あれですね、感情がよく動いていてかわいいんかなぁと思っています。

実はこの分野、上の「反応」「仕草」あたりと近しい部分でもあって、大分個人的には色々魅力の詰まっている項目だと思って
いるけど上手く言葉に出てこなかったので一旦は区切ろうかなと思います。
** エピソード
数々のエピソード、色々聞いているけどかわいいなぁ...ってなるのがチラホラある。

だきまくらくん抱いて寝てた話あったじゃないですか、あれめちゃかわいいな...って思いながら聞いてたりしました。夜桜み
あの抱き枕くんあんた幸せものな自覚持って...?みあちゃんをよろしく頼むな...側にいてやってくれな...

オタクなエピソードはめちゃくちゃかわいいよね。そもそもこう...「かわいい」が「かわいい」を推しているって時点でかわ
いさしかないんですよ。百合とかとも同じだけどかわいいxかわいい=かわいい理論。(これは苦手な場合もあると思うので明言
しておくけど、百合はすきだけどこれに関しては「かわいいものを推している推しがかわいい」という話であって百合として見
てるとかではないので安心してほしい。)
そもそも何かに夢中になっている人って人間として魅力的だなと思っていて、夜桜みあの場合夢中になってて楽しそうにしてい
るその姿がとってもかわいいな...ってなっています。

** 御姿
ん!あまりにも当たり前すぎて忘れていた事があります。御姿ですね!バリかわいい...かわいくない...?マジで...
おようふくもかわいいしお顔もかわいい。足とかすきだったりはするけどそれは「かわいい」とはベクトルが違うので一旦おあ
ずけ。

これは初期衣装では思ってなかったんですけど、第二衣装(って勝手に呼んでいる猫耳生える方のやつ)ではめちゃ綺麗なお姉さ
んファッションみたいにまとめてきているのにクマちゃんヘアピンはしっかり受け継いでいる所とかかわいいですよね。第二衣
装は「綺麗なお姉さん」っていうのに大分力を入れたデザインをしていると思っているんですよね。腕がスラッとするようなシャ
ツだとか、襟元が出来たりだとか、胸元のリボンを小さめにしたりとか、綺麗なおあしが出ていたりとか、お洒落なブーツ履い
てたりとか。や、みあちゃんがそこまで考えてたかは分かんないけど個人的な解釈としてね。でも、正直クマちゃんヘアピンっ
て「綺麗なお姉さん」っていうイメージとは違うと思うんですよ。なんとなくね。「綺麗なお姉さん」コンセプトだったら外さ
れちゃってもっとスマートなヘアピンになったりもしたと思うんです。それなのにクマちゃんヘアピンは生き残った。今迄の思
い出の入ったクマちゃんヘアピンをそのまま外せずに持ってきたのかな...とか、無意識のうちにそれは付けちゃったのかな...と
か考えるととってもかわいですよね。 


...ん？ここまで書いてて気付いたけどこれはただのオタクの妄想では...??


** 最後に
結構あれだね、「かわいさ」っていう所だけにフォーカスすると書けない事も多いですね...かわいさだけじゃないので夜桜み
あの取り柄は。マジで。寧ろかわいさ(特に声のかわいさ)はまだ入口でしかなくってそこから先へ進むと凄く沢山の魅力がある
人だなぁと思っています。ただそこはこの記事の範囲外なので一旦置いておきます。というか書ききれないよ普通に。
夜桜みあだいすきだぞ~!!


大分雑に書いた(しかも推敲をしていない)文なのですが読んでくれた人はありがとう!当方ただのオタク!!!
夜桜みあちゃんのチャンネル登録とTwitterのフォロー、よろしくお願いしますね。

