* ゆびきりを伝えて / 名取さな - を聞いて
:PROPERTIES:
:DATE: [2023-03-28 Tue 04:56]
:TAGS: :music:
:BLOG_POST_KIND: Memo
:BLOG_POST_PROGRESS: Published
:BLOG_POST_STATUS: Normal
:END:
:LOGBOOK:
CLOCK: [2023-03-28 Tue 04:57]--[2023-03-28 Tue 04:58] =>  0:01
:END:
  

これまためちゃくちゃ 色々刺さったので書いておく。動画はまだないとのこと。




「誰かの手を煩わせてる」の時点ですっっごく心にぐっ...ときた。なんだろう、上手くいえないけど私が普段
からとても気にしていて不安にしていることだから。なんだろうな、こうやってとても楽しそうにライブをして
きた名取ですら、やっぱりこういう日々はあったのかな、て思ったからなのだろうか。


名取も、「誰もが笑顔になれる私」を探してあれこれ試したりなんだりしたのかなって。色々上手くいかないこ
と沢山あるよね。空回りばかりして余計に分かんなくなっていって。世界が怖くなっていって。時間ばかりが早
く過ぎていって。色々言おうとしても言葉にならなくてため息を吐いたりもしたんだろうか。 


徐々にせんせえ方がどんな状態でもずっといてくれる、って信頼出来るようになっていって、それでちょっと荷
が下りたんだろうか。中々、緊張した状態を振り解くのって難しいよね。特に活動者みたいな「自分の魅力に対
して人が来てくれている」状態の場合、きっと変化によってそれを失うのが怖くなりそうだな、などと思ったり
した。よっぽどの信頼がないと出来ないよなぁって。


私もそんな存在になれるだろうか。ちゃんとリスナーとして、推しの安心に繋がるような良い存在でいれている
のだろうか。いっつも自問自答はしてっけど余計に考えてしまった。そういう存在でありたい。そういう存在に
なりたい。別段そうする必要性っていうものはないけれど、推しの存在から私が受け取っている物以上のものを
返せる存在でありたい。そうなりたい。


「誰もが笑顔になる私」っていうのはきっとある程度以上は自身に負荷がかかった存在ではあって、だからこそ
の「すきなままでいられそうかなあ」なのかなあって。私はとてもそれを掲げることは出来ない程に大変な存在
であるとは思うけど、それを掲げる程には名取はせんせえ方のことを考えていて、真剣で、色々悩んだりもした
んだろうなぁって。


「私はどんな私が好き？」って自分の観点を最終的に取り入れているの、とってもすきだよ。好きになれる自分
自身であること、とてもすてきなこと。


これ、本当に曲の感想文なのによくないなぁって思うんだけどどうしても夜桜みあの事が頭に浮かんでしまうん
だよな。正直書き出しから夜桜みあって書きそうになったしリアタイで聞いていた時もどうしてもみあちゃんの
ことが浮かんできてしまってもう感情がダメだった。


みあちゃんも(これは個人の解釈ではあるが)だいぶ人のこと考える人だし、黒猫さん達のこと考えてくれている
と感じるし、かつ大分考え込みすぎそうな気が勝手にしているからちょっと似たストーリーがありそうでこう...み
あちゃんは大丈夫だろうか...って勝手に心の中で思っていたりした。


大体は上で名取に思っていた事もそのまんまみあちゃんに関しても当て嵌るんだよな。人のことをとても考えて、
その結果として自分自身が嫌いになってたりとかしそうな...分からんけど...。
みあちゃんも色々試行錯誤したり、嫌になったり、空回りしたり、色々あるんだろうけど(そもそも人生ってい
うスケールで存在するよねってのもそうだが)、そこから乗り越えていけてるのだろうか。

みあちゃんは自分のことすきでいられているんだろうか。好かれようと無茶していないだろうか。これただの杞
憂民です杞憂民は早いとこ帰ってくださいgg。みあちゃんがみあちゃん自身の人生好きでいられるといいな、無
茶しないで楽しくいられるといいな、ってとても思っている。私はみあちゃんがすきだが、みあちゃんがみあちゃ
ん自身のことをすきでいられる状況の方がもっとすき。


そりゃ全ての人にすかれようとかは並大抵のことじゃないし、大分辛い道のりではあるよ。そもそもそこを目指
してんのかどうかも私は知らないけれども。でも、少なくとも今でさえ残っている黒猫さんたちはきっとどんな
事でもいてくれると思うしね。


別段私が言うことじゃないし、ここに書くだけで本人にわざわざ見えるようにはしたりしないが(何かの拍子に
見てくれてたらありがとう)名取の力だったりなんだりを貰って徐々に、徐々にでもみあちゃんの生涯に幸せが
増えていきますように。王様名取も言ってたけどみあちゃんが楽しむことで私達も楽しくなるしな。"楽しむフ
リ"ではなく。


本当に曲の感想？？って思われそうだけど本当に色々と考えてしまったんよな...すごいね、名取は。こんなに
も色々考えさせてしまうなんてさ。や、綺麗に纏めようとしてる？？？って思われそうだけどこれは本当に思っ
ている。ステージがなかったらこんな色々考えなかっただろうし、実際私は曲に対してこんな文字を書いたこと
がなかった。曲だけじゃなくパフォーマンス等も含まれてはしまうが、名取の力があってこその伝わってきたメッ
セージだったように思う。結局綺麗に纏めそうで草。
