name: Createt new issue from GitHub Issue

on:
  issue_comment:
    types: [created]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    if: |
      github.event.issue.author_association == 'OWNER'
      && github.event.comment.author_association == 'OWNER'
    steps:
      - uses: actions/checkout@v4
      - name: Check issue labels
        if: contains(github.event.issue.labels.*.name, 'automation/new-post') != true
        run: exit 0
      - name: Check command
        if: github.event.comment.body != '/p'
        run: exit 0
      - name: Define title
        id: define_title
        run: |
          title=$(echo "${{ github.event.issue.title }}" | sed -r 's/([a-z0-9])([A-Z])/\1-\2/g; s/ /-/g' | tr '[A-Z]' '[a-z]')
          echo "title=$title" >> "$GITHUB_OUTPUT"
      - name: Create Content File
        run: |
          printf "%s" "${BODY}" | awk -v dt="$(TZ=-9 date --rfc-3339='seconds')" '
            BEGIN {
              frontmatter_count=0
              print "---"
            }
            /^---$/ {
              frontmatter_count++
              print
              next
            }
            frontmatter_count == 1 && /^publishDate:/ {
              print "publishDate: [" dt "]"
              next
            }
            frontmatter_count == 1 && /^modDatetime:/ {
              print "modDatetime: [" dt "]"
              next
            }
            { print }
          ' >> posts/${{ steps.define_title.outputs.title }}.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BODY: ${{ github.event.issue.body }}
      - name: Commit Content File
        id: commit_file
        run: |
            git config user.name github-actions
            git config user.email github-actions@github.com

            branch="new_post/${{ steps.define_title.outputs.title }}"
            git switch -c $branch
            git add *
            git commit -m "feat: new post"
            git push origin "$branch"
            echo "branch=$branch" >> "$GITHUB_OUTPUT"
      - name: Create PullRequest
        id: create_pr
        run: |
          pr_url=$(gh pr create --title "${{ github.event.issue.title }}" --body "Closes \#${{ github.event.issue.number}}" --base source --head ${{ steps.commit_file.outputs.branch }})
          echo "pr_url=${pr_url}" >> "$GITHUB_OUTPUT"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Comment progress on issue (success)
        if: success()
        run: gh issue comment "${{ github.event.issue.number }}" --body "Converted to PR successfully✨\n${{ steps.create_pr.outputs.pr_url }}"
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Comment progress on issue (failure)
        if: failure()
        run: gh issue comment "${{ github.event.issue.number }}" --body "Failed to convert to PR:;(∩´﹏`∩);:"
        env:
          GH_TOKEN: ${{ github.token }}