name: Publish
on:
  push:
    branches: [source]
  workflow_dispatch:

jobs:
  runPublish:
    name: run publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
      - name: run publish
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git switch source
          make blog-publish
          git push origin publish
      - uses: actions/upload-pages-artifact@v3
        with:
          path: "_site/"
  deploy:
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    needs: runPublish
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deply to Github Pages
        id: deployment
        uses: actions/deploy-pages@v4
